# Generated by Django 2.1.7 on 2020-03-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='diabetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('gender', models.CharField(choices=[(None, 'Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('total_cholestrol', models.IntegerField(blank=True, null=True)),
                ('hdl_cholestrol', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('waist', models.IntegerField(blank=True, null=True)),
                ('hip', models.IntegerField(blank=True, null=True)),
                ('physically_active', models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('eat', models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('bp', models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('relative_diabetes', models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('parent_diabetes', models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('glucose', models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('smoking', models.CharField(choices=[(None, 'Select'), ('Never smoked', 'Never smoked'), ('Ex-smoker', 'Ex-smoker'), ('Low-smoker(<=10/month)', 'Low-smoker(<=10/month)'), ('Mid-smoker(11-20/month)', 'Mid-smoker(11-20/month)'), ('High-smoker(>20/month)', 'High-smoker(>20/month)')], max_length=100, null=True)),
                ('heart_disease', models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('depression', models.CharField(choices=[(None, 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('HbA1c', models.IntegerField(blank=True, null=True)),
                ('haem', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
